<?php
/**
 * Autoloader for the bundled PHP AI Client library.
 *
 * This file is generated by tools/php-ai-client/installer.sh.
 * Do not edit directly.
 *
 * @package ZelocoreCMS
 * @subpackage AI
 * @since 7.0.0
 */

spl_autoload_register(
	static function ( $class_name ) {
		// Namespace prefix for the AI client.
		$client_prefix     = 'ZelocoreCMS\\AiClient\\';
		$client_prefix_len = 21; // strlen( 'ZelocoreCMS\\AiClient\\' )

		// Namespace prefix for scoped dependencies (includes Psr\*, Http\*, etc.).
		$scoped_prefix     = 'ZelocoreCMS\\AiClientDependencies\\';
		$scoped_prefix_len = 33; // strlen( 'ZelocoreCMS\\AiClientDependencies\\' )

		$base_dir = __DIR__;

		// 1. ZelocoreCMS\AiClient\* → src/
		if ( 0 === strncmp( $class_name, $client_prefix, $client_prefix_len ) ) {
			$relative_class = substr( $class_name, $client_prefix_len );
			$file           = $base_dir . '/src/' . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
			}
			return;
		}

		// 2. ZelocoreCMS\AiClientDependencies\* → third-party/ (strip prefix).
		if ( 0 === strncmp( $class_name, $scoped_prefix, $scoped_prefix_len ) ) {
			$relative_class = substr( $class_name, $scoped_prefix_len );
			$file           = $base_dir . '/third-party/' . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
			}
			return;
		}
	}
);
